name: Deploy Hexo

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # 使用与本地开发一致的Node.js版本

      - name: Install Dependencies
        run: |
          npm install -g hexo-cli
          npm install

      - name: Generate Static Files
        run: |
          hexo clean
          hexo generate
          # 可选：检查生成的文件
          ls -la public/ || echo "Public directory does not exist."

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public