name: Deploy Hexo Blog

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    # 1. 检出博客源代码
    - name: Checkout source code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 2. 设置 Node.js 环境
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: package-lock.json

    # 3. 缓存 Node.js 模块
    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    # 4. 安装 Hexo CLI 和项目依赖
    - name: Install dependencies
      run: |
        npm install -g hexo-cli
        npm install

    # 5. 生成静态文件
    - name: Generate static files
      run: |
        hexo clean
        hexo generate

    # 6. 部署到 GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        publish_branch: gh-pages